"""
    This file is generated by running bin/generate_classes.py and should not be edited manually.
"""
from ctypes import *
SHARED_MEMORY_VERSION = 5
STRING_LENGTH_MAX = 64
STORED_PARTICIPANTS_MAX = 64
TYRE_FRONT_LEFT = 0
TYRE_FRONT_RIGHT = 1
TYRE_REAR_LEFT = 2
TYRE_REAR_RIGHT = 3
TYRE_MAX = 4
VEC_X = 0
VEC_Y = 1
VEC_Z = 2
VEC_MAX = 3
GAME_EXITED = 0
GAME_FRONT_END = 1
GAME_INGAME_PLAYING = 2
GAME_INGAME_PAUSED = 3
GAME_MAX = 4
SESSION_INVALID = 0
SESSION_PRACTICE = 1
SESSION_TEST = 2
SESSION_QUALIFY = 3
SESSION_FORMATION_LAP = 4
SESSION_RACE = 5
SESSION_TIME_ATTACK = 6
SESSION_MAX = 7
RACESTATE_INVALID = 0
RACESTATE_NOT_STARTED = 1
RACESTATE_RACING = 2
RACESTATE_FINISHED = 3
RACESTATE_DISQUALIFIED = 4
RACESTATE_RETIRED = 5
RACESTATE_DNF = 6
RACESTATE_MAX = 7
SECTOR_INVALID = 0
SECTOR_START = 1
SECTOR_SECTOR1 = 2
SECTOR_SECTOR2 = 3
SECTOR_FINISH = 4
SECTOR_STOP = 5
SECTOR_MAX = 6
FLAG_COLOUR_NONE = 0
FLAG_COLOUR_GREEN = 1
FLAG_COLOUR_BLUE = 2
FLAG_COLOUR_WHITE = 3
FLAG_COLOUR_YELLOW = 4
FLAG_COLOUR_DOUBLE_YELLOW = 5
FLAG_COLOUR_BLACK = 6
FLAG_COLOUR_CHEQUERED = 7
FLAG_COLOUR_MAX = 8
FLAG_REASON_NONE = 0
FLAG_REASON_SOLO_CRASH = 1
FLAG_REASON_VEHICLE_CRASH = 2
FLAG_REASON_VEHICLE_OBSTRUCTION = 3
FLAG_REASON_MAX = 4
PIT_MODE_NONE = 0
PIT_MODE_DRIVING_INTO_PITS = 1
PIT_MODE_IN_PIT = 2
PIT_MODE_DRIVING_OUT_OF_PITS = 3
PIT_MODE_IN_GARAGE = 4
PIT_MODE_MAX = 5
PIT_SCHEDULE_NONE = 0
PIT_SCHEDULE_STANDARD = 1
PIT_SCHEDULE_DRIVE_THROUGH = 2
PIT_SCHEDULE_STOP_GO = 3
PIT_SCHEDULE_MAX = 4
CAR_HEADLIGHT = 1
CAR_ENGINE_ACTIVE = 2
CAR_ENGINE_WARNING = 4
CAR_SPEED_LIMITER = 8
CAR_ABS = 16
CAR_HANDBRAKE = 32
TYRE_ATTACHED = 1
TYRE_INFLATED = 2
TYRE_IS_ON_GROUND = 4
TERRAIN_ROAD = 0
TERRAIN_LOW_GRIP_ROAD = 1
TERRAIN_BUMPY_ROAD1 = 2
TERRAIN_BUMPY_ROAD2 = 3
TERRAIN_BUMPY_ROAD3 = 4
TERRAIN_MARBLES = 5
TERRAIN_GRASSY_BERMS = 6
TERRAIN_GRASS = 7
TERRAIN_GRAVEL = 8
TERRAIN_BUMPY_GRAVEL = 9
TERRAIN_RUMBLE_STRIPS = 10
TERRAIN_DRAINS = 11
TERRAIN_TYREWALLS = 12
TERRAIN_CEMENTWALLS = 13
TERRAIN_GUARDRAILS = 14
TERRAIN_SAND = 15
TERRAIN_BUMPY_SAND = 16
TERRAIN_DIRT = 17
TERRAIN_BUMPY_DIRT = 18
TERRAIN_DIRT_ROAD = 19
TERRAIN_BUMPY_DIRT_ROAD = 20
TERRAIN_PAVEMENT = 21
TERRAIN_DIRT_BANK = 22
TERRAIN_WOOD = 23
TERRAIN_DRY_VERGE = 24
TERRAIN_EXIT_RUMBLE_STRIPS = 25
TERRAIN_GRASSCRETE = 26
TERRAIN_LONG_GRASS = 27
TERRAIN_SLOPE_GRASS = 28
TERRAIN_COBBLES = 29
TERRAIN_SAND_ROAD = 30
TERRAIN_BAKED_CLAY = 31
TERRAIN_ASTROTURF = 32
TERRAIN_SNOWHALF = 33
TERRAIN_SNOWFULL = 34
TERRAIN_MAX = 35
CRASH_DAMAGE_NONE = 0
CRASH_DAMAGE_OFFTRACK = 1
CRASH_DAMAGE_LARGE_PROP = 2
CRASH_DAMAGE_SPINNING = 3
CRASH_DAMAGE_ROLLING = 4
CRASH_MAX = 5

class ParticipantInfo(Structure):
    _fields_ = [
     (
      'mIsActive', c_bool),
     (
      'mName', c_char * STRING_LENGTH_MAX),
     (
      'mWorldPosition', c_float * VEC_MAX),
     (
      'mCurrentLapDistance', c_float),
     (
      'mRacePosition', c_uint),
     (
      'mLapsCompleted', c_uint),
     (
      'mCurrentLap', c_uint),
     (
      'mCurrentSector', c_uint)]


class pcarsPhysics(Structure):
    _fields_ = [
     (
      'mVersion', c_uint),
     (
      'mBuildVersionNumber', c_uint),
     (
      'mGameState', c_uint),
     (
      'mSessionState', c_uint),
     (
      'mRaceState', c_uint),
     (
      'mViewedParticipantIndex', c_int),
     (
      'mNumParticipants', c_int),
     (
      'mParticipantInfo', ParticipantInfo * STORED_PARTICIPANTS_MAX),
     (
      'mUnfilteredThrottle', c_float),
     (
      'mUnfilteredBrake', c_float),
     (
      'mUnfilteredSteering', c_float),
     (
      'mUnfilteredClutch', c_float),
     (
      'mCarName', c_char * STRING_LENGTH_MAX),
     (
      'mCarClassName', c_char * STRING_LENGTH_MAX),
     (
      'mLapsInEvent', c_uint),
     (
      'mTrackLocation', c_char * STRING_LENGTH_MAX),
     (
      'mTrackVariation', c_char * STRING_LENGTH_MAX),
     (
      'mTrackLength', c_float),
     (
      'mLapInvalidated', c_bool),
     (
      'mBestLapTime', c_float),
     (
      'mLastLapTime', c_float),
     (
      'mCurrentTime', c_float),
     (
      'mSplitTimeAhead', c_float),
     (
      'mSplitTimeBehind', c_float),
     (
      'mSplitTime', c_float),
     (
      'mEventTimeRemaining', c_float),
     (
      'mPersonalFastestLapTime', c_float),
     (
      'mWorldFastestLapTime', c_float),
     (
      'mCurrentSector1Time', c_float),
     (
      'mCurrentSector2Time', c_float),
     (
      'mCurrentSector3Time', c_float),
     (
      'mFastestSector1Time', c_float),
     (
      'mFastestSector2Time', c_float),
     (
      'mFastestSector3Time', c_float),
     (
      'mPersonalFastestSector1Time', c_float),
     (
      'mPersonalFastestSector2Time', c_float),
     (
      'mPersonalFastestSector3Time', c_float),
     (
      'mWorldFastestSector1Time', c_float),
     (
      'mWorldFastestSector2Time', c_float),
     (
      'mWorldFastestSector3Time', c_float),
     (
      'mHighestFlagColour', c_uint),
     (
      'mHighestFlagReason', c_uint),
     (
      'mPitMode', c_uint),
     (
      'mPitSchedule', c_uint),
     (
      'mCarFlags', c_uint),
     (
      'mOilTempCelsius', c_float),
     (
      'mOilPressureKPa', c_float),
     (
      'mWaterTempCelsius', c_float),
     (
      'mWaterPressureKPa', c_float),
     (
      'mFuelPressureKPa', c_float),
     (
      'mFuelLevel', c_float),
     (
      'mFuelCapacity', c_float),
     (
      'mSpeed', c_float),
     (
      'mRpm', c_float),
     (
      'mMaxRPM', c_float),
     (
      'mBrake', c_float),
     (
      'mThrottle', c_float),
     (
      'mClutch', c_float),
     (
      'mSteering', c_float),
     (
      'mGear', c_int),
     (
      'mNumGears', c_int),
     (
      'mOdometerKM', c_float),
     (
      'mAntiLockActive', c_bool),
     (
      'mLastOpponentCollisionIndex', c_int),
     (
      'mLastOpponentCollisionMagnitude', c_float),
     (
      'mBoostActive', c_bool),
     (
      'mBoostAmount', c_float),
     (
      'mOrientation', c_float * VEC_MAX),
     (
      'mLocalVelocity', c_float * VEC_MAX),
     (
      'mWorldVelocity', c_float * VEC_MAX),
     (
      'mAngularVelocity', c_float * VEC_MAX),
     (
      'mLocalAcceleration', c_float * VEC_MAX),
     (
      'mWorldAcceleration', c_float * VEC_MAX),
     (
      'mExtentsCentre', c_float * VEC_MAX),
     (
      'mTyreFlags', c_uint * TYRE_MAX),
     (
      'mTerrain', c_uint * TYRE_MAX),
     (
      'mTyreY', c_float * TYRE_MAX),
     (
      'mTyreRPS', c_float * TYRE_MAX),
     (
      'mTyreSlipSpeed', c_float * TYRE_MAX),
     (
      'mTyreTemp', c_float * TYRE_MAX),
     (
      'mTyreGrip', c_float * TYRE_MAX),
     (
      'mTyreHeightAboveGround', c_float * TYRE_MAX),
     (
      'mTyreLateralStiffness', c_float * TYRE_MAX),
     (
      'mTyreWear', c_float * TYRE_MAX),
     (
      'mBrakeDamage', c_float * TYRE_MAX),
     (
      'mSuspensionDamage', c_float * TYRE_MAX),
     (
      'mBrakeTempCelsius', c_float * TYRE_MAX),
     (
      'mTyreTreadTemp', c_float * TYRE_MAX),
     (
      'mTyreLayerTemp', c_float * TYRE_MAX),
     (
      'mTyreCarcassTemp', c_float * TYRE_MAX),
     (
      'mTyreRimTemp', c_float * TYRE_MAX),
     (
      'mTyreInternalAirTemp', c_float * TYRE_MAX),
     (
      'mCrashState', c_uint),
     (
      'mAeroDamage', c_float),
     (
      'mEngineDamage', c_float),
     (
      'mAmbientTemperature', c_float),
     (
      'mTrackTemperature', c_float),
     (
      'mRainDensity', c_float),
     (
      'mWindSpeed', c_float),
     (
      'mWindDirectionX', c_float),
     (
      'mWindDirectionY', c_float),
     (
      'mCloudBrightness', c_float)]


pcarsMapTag = '$pcars$'
pcarsMapHandle = None